#ifndef PP_CHAR_H
#define PP_CHAR_H

#define PP_CHAR(X) PP_JOIN(PP_CHAR_, X)
#define PP_CHAR_0 [NUL]
#define PP_CHAR_1 [SOH]
#define PP_CHAR_2 [STX]
#define PP_CHAR_3 [ETX]
#define PP_CHAR_4 [EOT]
#define PP_CHAR_5 [ENQ]
#define PP_CHAR_6 [ACK]
#define PP_CHAR_7 [BEL]
#define PP_CHAR_8 [BS]
#define PP_CHAR_9     
#define PP_CHAR_10 \

#define PP_CHAR_11 [VT]
#define PP_CHAR_12 [FF]
#define PP_CHAR_13 [CR]
#define PP_CHAR_14 [SO]
#define PP_CHAR_15 [SI]
#define PP_CHAR_16 [DLE]
#define PP_CHAR_17 [DC1]
#define PP_CHAR_18 [DC2]
#define PP_CHAR_19 [DC3]
#define PP_CHAR_20 [DC4]
#define PP_CHAR_21 [NAK]
#define PP_CHAR_22 [SYN]
#define PP_CHAR_23 [ETB]
#define PP_CHAR_24 [CAN]
#define PP_CHAR_25 [EM]
#define PP_CHAR_26 [SUB]
#define PP_CHAR_27 [ESC]
#define PP_CHAR_28 [FS]
#define PP_CHAR_29 [GS]
#define PP_CHAR_30 [RS]
#define PP_CHAR_31 [US]
#define PP_CHAR_32  
#define PP_CHAR_33 !
#define PP_CHAR_34 [DQ]
#define PP_CHAR_35 #
#define PP_CHAR_36 $
#define PP_CHAR_37 %
#define PP_CHAR_38 &
#define PP_CHAR_39 [SQ]
#define PP_CHAR_40 (
#define PP_CHAR_41 )
#define PP_CHAR_42 *
#define PP_CHAR_43 +
#define PP_CHAR_44 ,
#define PP_CHAR_45 -
#define PP_CHAR_46 .
#define PP_CHAR_47 /
#define PP_CHAR_48 0
#define PP_CHAR_49 1
#define PP_CHAR_50 2
#define PP_CHAR_51 3
#define PP_CHAR_52 4
#define PP_CHAR_53 5
#define PP_CHAR_54 6
#define PP_CHAR_55 7
#define PP_CHAR_56 8
#define PP_CHAR_57 9
#define PP_CHAR_58 :
#define PP_CHAR_59 ;
#define PP_CHAR_60 <
#define PP_CHAR_61 =
#define PP_CHAR_62 >
#define PP_CHAR_63 ?
#define PP_CHAR_64 @
#define PP_CHAR_65 A
#define PP_CHAR_66 B
#define PP_CHAR_67 C
#define PP_CHAR_68 D
#define PP_CHAR_69 E
#define PP_CHAR_70 F
#define PP_CHAR_71 G
#define PP_CHAR_72 H
#define PP_CHAR_73 I
#define PP_CHAR_74 J
#define PP_CHAR_75 K
#define PP_CHAR_76 L
#define PP_CHAR_77 M
#define PP_CHAR_78 N
#define PP_CHAR_79 O
#define PP_CHAR_80 P
#define PP_CHAR_81 Q
#define PP_CHAR_82 R
#define PP_CHAR_83 S
#define PP_CHAR_84 T
#define PP_CHAR_85 U
#define PP_CHAR_86 V
#define PP_CHAR_87 W
#define PP_CHAR_88 X
#define PP_CHAR_89 Y
#define PP_CHAR_90 Z
#define PP_CHAR_91 [
#define PP_CHAR_92 \
#define PP_CHAR_93 ]
#define PP_CHAR_94 ^
#define PP_CHAR_95 _
#define PP_CHAR_96 `
#define PP_CHAR_97 a
#define PP_CHAR_98 b
#define PP_CHAR_99 c
#define PP_CHAR_100 d
#define PP_CHAR_101 e
#define PP_CHAR_102 f
#define PP_CHAR_103 g
#define PP_CHAR_104 h
#define PP_CHAR_105 i
#define PP_CHAR_106 j
#define PP_CHAR_107 k
#define PP_CHAR_108 l
#define PP_CHAR_109 m
#define PP_CHAR_110 n
#define PP_CHAR_111 o
#define PP_CHAR_112 p
#define PP_CHAR_113 q
#define PP_CHAR_114 r
#define PP_CHAR_115 s
#define PP_CHAR_116 t
#define PP_CHAR_117 u
#define PP_CHAR_118 v
#define PP_CHAR_119 w
#define PP_CHAR_120 x
#define PP_CHAR_121 y
#define PP_CHAR_122 z
#define PP_CHAR_123 {
#define PP_CHAR_124 |
#define PP_CHAR_125 }
#define PP_CHAR_126 ~
#define PP_CHAR_127 DEL

#endif