#ifndef RECR_H
#define RECR_H

#include "CORE.h"
#include "COND.h"

#define $0 0
#define $1 1

/*!
 * Recursion Example
 * =================
 *
 * #define RCOND($, X) BOOL(X)
 * #define RMACRO($, X) X
 * #define RUPDATE($, X) SUB($, X, 2)
 * #define RFINALLY($, X) DONE
 *
 * #define RTEST($, X) JOIN(RECR_D, $)(INC($), RCOND, RMACRO, RUPDATE, RFINALLY, X)
 *
 * RTEST($, 10) => 10 8 6 4 2 
 * 
 */
 
#define RECR_D0($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D1($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D2($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D3($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D4($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D5($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D6($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D7($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D8($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D9($, C, M, U, E, X)   JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D10($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D11($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D12($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D13($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D14($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D15($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D16($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D17($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D18($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D19($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D20($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D21($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D22($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D23($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D24($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D25($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D26($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D27($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D28($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D29($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D30($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D31($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D32($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D33($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D34($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D35($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D36($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D37($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D38($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D39($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D40($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D41($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D42($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D43($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D44($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D45($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D46($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D47($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D48($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D49($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D50($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D51($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D52($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D53($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D54($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D55($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D56($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D57($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D58($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D59($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D60($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D61($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D62($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D63($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D64($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D65($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D66($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D67($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D68($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D69($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D70($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D71($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D72($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D73($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D74($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D75($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D76($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D77($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D78($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D79($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D80($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D81($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D82($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D83($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D84($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D85($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D86($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D87($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D88($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D89($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D90($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D91($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D92($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D93($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D94($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D95($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D96($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D97($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D98($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)
#define RECR_D99($, C, M, U, E, X)  JOIN(RECR_A, $)(INC($), C, M, U, E, X)

#define RECR_A0($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A1($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A2($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A3($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A4($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A5($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A6($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A7($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A8($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A9($, C, M, U, E, X)   IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A10($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A11($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A12($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A13($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A14($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A15($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A16($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A17($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A18($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A19($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A20($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A21($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A22($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A23($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A24($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A25($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A26($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A27($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A28($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A29($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A30($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A31($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A32($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A33($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A34($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A35($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A36($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A37($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A38($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A39($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A40($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A41($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A42($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A43($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A44($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A45($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A46($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A47($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A48($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A49($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A50($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A51($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A52($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A53($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A54($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A55($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A56($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A57($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A58($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A59($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A60($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A61($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A62($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A63($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A64($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A65($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A66($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A67($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A68($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A69($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A70($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A71($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A72($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A73($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A74($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A75($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A76($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A77($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A78($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A79($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A80($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A81($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A82($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A83($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A84($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A85($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A86($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A87($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A88($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A89($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A90($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A91($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A92($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A93($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A94($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A95($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A96($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A97($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A98($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )
#define RECR_A99($, C, M, U, E, X)  IF_ELSE( C($, X), M($, X) JOIN(RECR_D, $)(INC($), C, M, U, E, U($, X)), E($, X) )

#endif